version: '3.4'

services:
  cleancodelab4:
    image: ${DOCKER_REGISTRY-}cleancodelab4
    build:
      context: .
      dockerfile: CleanCodeLab4/Dockerfile
    ports:
      - "80:80"

  addition:
    image: ${DOCKER_REGISTRY-}lab4additioncalculationservice
    build:
      context: .
      dockerfile: Lab4AdditionCalculationService/Dockerfile

  division:
    image: ${DOCKER_REGISTRY-}lab4divisioncalculationservice
    build:
      context: .
      dockerfile: Lab4DivisionCalculationService/Dockerfile

  multiplication:
    image: ${DOCKER_REGISTRY-}lab4multiplicationcalculationservice
    build:
      context: .
      dockerfile: Lab4MultiplicationCalculationService/Dockerfile

  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

