version: '3.4'

services:
  cleancodelab4:
    image: ${DOCKER_REGISTRY-}cleancodelab4
    networks:
      - Lab4Network
    build:
      context: .
      dockerfile: ./CleanCodeLab4/Dockerfile
    expose:
      - 80

  addition:
    image: ${DOCKER_REGISTRY-}lab4additioncalculationservice
    networks:
      - Lab4Network
    build:
      context: ./Lab4AdditionCalculationService
      dockerfile: Dockerfile

  division:
    image: ${DOCKER_REGISTRY-}lab4divisioncalculationservice
    networks:
      - Lab4Network
    build:
      context: ./Lab4DivisionCalculationService
      dockerfile: Dockerfile

  multiplication:
    image: ${DOCKER_REGISTRY-}lab4multiplicationcalculationservice
    networks:
      - Lab4Network
    build:
      context: ./Lab4MultiplicationCalculationService
      dockerfile: Dockerfile

  mysql:
    image: ${DOCKER_REGISTRY-}lab4mysql
    networks:
      - Lab4Network
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: ./Lab4MySql/Dockerfile
    expose:
      - 6000

  db:
    image: mysql
    networks:
      - Lab4Network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: 0.0.0.0/0.0.0.0
    ports:
      - 3306:3306

  adminer:
    image: adminer
    networks:
      - Lab4Network
    restart: always
    ports:
      - 8080:8080

networks:
  Lab4Network: {}
